import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { createServerClient } from '@supabase/ssr';
import { createClient } from '@supabase/supabase-js';

const base=process.env.ZINGPOSTS_URL??'http://localhost:3000'; const supabaseUrl=process.env.SUPABASE_URL; const anonKey=process.env.SUPABASE_ANON_KEY; const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
assert.ok(supabaseUrl&&anonKey&&serviceKey,'SUPABASE_URL, SUPABASE_ANON_KEY, and SUPABASE_SERVICE_ROLE_KEY are required.');
const database=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}); const runId=randomUUID().replaceAll('-','').slice(0,16); const email=`human-auth-${runId}@example.test`; const password=randomBytes(24).toString('base64url');
let userId=''; let authUserId='';

async function cleanup(){
  if(userId){await database.from('account_identities').delete().eq('workspace_user_id',userId);await database.from('confirmations').delete().eq('user_id',userId);await database.from('activity_events').delete().eq('user_id',userId);await database.from('alerts').delete().eq('user_id',userId);await database.from('saved_items').delete().eq('user_id',userId);const {data:boards}=await database.from('boards').select('id').eq('user_id',userId);if(boards?.length)await database.from('board_items').delete().in('board_id',boards.map(board=>board.id));await database.from('boards').delete().eq('user_id',userId);await database.from('user_preferences').delete().eq('user_id',userId);await database.from('users').delete().eq('id',userId)}
  if(authUserId)await database.auth.admin.deleteUser(authUserId);
}

try{
  const prototype=await fetch(`${base}/api/session`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'sign-in',name:'Human auth integration',email})}); assert.equal(prototype.ok,true); const prototypeCookie=prototype.headers.getSetCookie?.()[0]?.split(';')[0]??prototype.headers.get('set-cookie')?.split(';')[0];
  const initialResponse=await fetch(`${base}/api/state`,{headers:{cookie:prototypeCookie}}); const initial=await initialResponse.json(); userId=initial.user.userId; assert.equal(initial.verification.status,'unverified');
  const created=await database.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{display_name:'Human auth integration'}}); assert.equal(created.error,null,created.error?.message); authUserId=created.data.user.id; const timestamp=new Date().toISOString(); const linked=await database.from('account_identities').insert({workspace_user_id:userId,auth_user_id:authUserId,verified_email:email,verified_at:timestamp,created_at:timestamp,updated_at:timestamp}); assert.equal(linked.error,null,linked.error?.message);
  const generated=await database.auth.admin.generateLink({type:'magiclink',email}); assert.equal(generated.error,null,generated.error?.message); const tokenHash=generated.data.properties?.hashed_token; assert.ok(tokenHash,'Supabase should generate a token hash for a server-side magic link.');
  const crossBrowserCallback=await fetch(`${base}/auth/callback?token_hash=${encodeURIComponent(tokenHash)}&type=email`,{redirect:'manual'}); assert.equal(crossBrowserCallback.status,307); const callbackLocation=new URL(crossBrowserCallback.headers.get('location')??'',base); assert.equal(callbackLocation.searchParams.get('auth_status'),'signed_in'); assert.equal(callbackLocation.searchParams.has('token_hash'),false,'the one-use token hash must not remain in the final browser URL'); assert.equal(callbackLocation.searchParams.has('type'),false); const callbackCookies=(crossBrowserCallback.headers.getSetCookie?.()??[]).map(value=>value.split(';')[0]).join('; '); assert.match(callbackCookies,/zingposts-session=/,'token-hash callback should create the durable Zingposts session without a PKCE browser cookie');
  const crossBrowserStateResponse=await fetch(`${base}/api/state`,{headers:{cookie:callbackCookies}}); assert.equal(crossBrowserStateResponse.ok,true); const crossBrowserState=await crossBrowserStateResponse.json(); assert.equal(crossBrowserState.authenticated,true); assert.equal(crossBrowserState.user.email,email);
  const generatedOtp=await database.auth.admin.generateLink({type:'magiclink',email}); assert.equal(generatedOtp.error,null,generatedOtp.error?.message); const emailOtp=generatedOtp.data.properties?.email_otp; assert.match(emailOtp??'',/^\d{8}$/,'current Supabase email OTPs should contain eight digits');
  const verifiedOtp=await fetch(`${base}/api/auth/verify`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,token:emailOtp})}); assert.equal(verifiedOtp.ok,true); const verifiedOtpBody=await verifiedOtp.json(); assert.equal(verifiedOtpBody.authenticated,true);
  const blockedLegacy=await fetch(`${base}/api/state`,{headers:{cookie:prototypeCookie}}); const blockedState=await blockedLegacy.json(); assert.equal(blockedState.authenticated,false,'a verified workspace must reject the old deterministic-email cookie');
  const jar=new Map(); const auth=createServerClient(supabaseUrl,anonKey,{cookies:{getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:items=>items.forEach(item=>jar.set(item.name,item.value))},auth:{flowType:'pkce'}}); const signedIn=await auth.auth.signInWithPassword({email,password}); assert.equal(signedIn.error,null,signedIn.error?.message);
  const supabaseCookies=[...jar].map(([name,value])=>`${name}=${value}`).join('; '); const authenticated=await fetch(`${base}/api/state`,{headers:{cookie:`${prototypeCookie}; ${supabaseCookies}`}}); assert.equal(authenticated.ok,true); const state=await authenticated.json(); assert.equal(state.authenticated,true); assert.equal(state.authMode,'supabase-email-link'); assert.equal(state.verification.status,'verified'); assert.equal(state.user.email,email);
  const authStatusResponse=await fetch(`${base}/api/state`,{method:'POST',headers:{'content-type':'application/json',cookie:`${prototypeCookie}; ${supabaseCookies}`},body:JSON.stringify({action:'get_auth_status',input:{},actor:{type:'human',name:'Spoofed client name'}})}); const authStatus=await authStatusResponse.json(); assert.equal(authStatus.result.authLevel,'verified-human'); assert.equal(authStatus.result.supabaseAuthenticated,true); assert.equal(authStatus.result.user.displayName,'Human auth integration');
  const browserCookie=`${prototypeCookie}; ${supabaseCookies}`;
  const browserAgent=async(action,input={})=>{const response=await fetch(`${base}/api/state`,{method:'POST',headers:{'content-type':'application/json',cookie:browserCookie},body:JSON.stringify({action,input,actor:{type:'agent',name:'Spoofed agent name'}})});const body=await response.json();return {response,body}};
  const bootstrap=await browserAgent('get_agent_bootstrap',{activeCapability:'marketplace'});assert.equal(bootstrap.response.ok,true);assert.equal(bootstrap.body.result.canonicalAgent.id,'browser_session');assert.equal(bootstrap.body.result.canonicalAgent.name,'Browser agent via Human auth integration');assert.equal(bootstrap.body.result.canonicalAgent.access,'browser-delegated');
  const boards=await browserAgent('list_boards');assert.equal(boards.response.ok,true,'signed-in browser agent should use safe private tools without a separate agent code');
  const alert=await browserAgent('create_alert_draft',{name:`Human auth ${runId}`,query:'Virginia sailboats under $2,000',criteria:{}});assert.equal(alert.response.ok,true);
  const gate=await browserAgent('enable_alert',{alertId:alert.body.result.alertId,confirmed:true});assert.equal(gate.response.ok,true);assert.equal(gate.body.result.confirmationRequired,true);assert.equal(gate.body.result.humanRequired,true,'browser delegation must not confirm its own consequential request');
  console.log(JSON.stringify({ok:true,crossBrowserMagicLink:true,eightDigitEmailOtp:true,legacyPrototypeAccessDisabled:true,supabaseSessionRequired:true,verifiedHumanIdentityServerDerived:true,browserSessionDelegation:true,spoofedAgentIdentityRejected:true,consequentialHumanGatePreserved:true},null,2));
} finally {
  await cleanup();
}
